name: CI

on:
  pull_request:
  push:
    branches:
      - ssl-app

jobs:
  test:
    runs-on: ubuntu-20.04
    env:
      MIX_ENV: test
    strategy:
      fail-fast: false
      matrix:
        include:
          - elixir: "1.9.0"
            otp: "20.0"
          - elixir: "1.10.0"
            otp: "21.0"
          - elixir: "1.11.0"
            otp: "21.0"
          - elixir: "1.12.0"
            otp: "22.0"
          - elixir: "1.13.0"
            otp: "22.0"
          - elixir: "1.14.0"
            otp: "23.0"
          - elixir: "1.15.0"
            otp: "24.0"
          - elixir: "1.16.0"
            otp: "24.0"
          - elixir: "1.16.0"
            otp: "24.3.4.16"
          - elixir: "1.16.0"
            otp: "25.0"
          - elixir: "1.16.0"
            otp: "25.3.2.9"
          - elixir: "1.16.0"
            otp: "26.0"
          - elixir: "1.16.0"
            otp: "26.2.2"
    steps:
      - uses: actions/checkout@v2

      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}

      - run: mix deps.get --only test
      - run: mix deps.compile
      - run: mix test
